export enum SelectQueryKeyEnum {
  COUNTRY = "COUNTRY",
}

export enum AdminQueryKeyEnum {
  AGENCY = "AGENCY",
  COMPANY = "COMPANY",
  JOB = "JOB",
  INTERVIEW = "INTERVIEW",
  EMPLOYMENT = "EMPLOYMENT",
  EMPLOYEE = "EMPLOYEE",
  CORPORATE = "CORPORATE",
  STATISTIC = "STATISTIC",
}
